### ISSUE TITLE
Align properties with schema.org?

### ISSUE THREAD

**Issue by jacqui** [glitchdigital/structured-data-api#5]
I looked over the existing models and found disconnects between field names in this repo and schema.org. If we're going with matching schema.org, we should match up, no? Is this the idea?

* organization model: dateFounded -> foundingDate
* person: birth & death dates etc.

http://schema.org/Person
http://schema.org/Organization

**Comment by jacqui** [comment]
the event model matches http://schema.org/Event pretty well :)

**Comment by iaincollins** [comment]
Yeah we should I think - that's the idea!

I thought it might be good to only support a subset of the more common values by default rather than the entire schema, what do you think?

We could just support the entire schema, and have a toJSON routine that removes any unused (null) fields when returning objects (so you are not getting back loads of unused fields when fetching an object).

Obviously there should be endpoints to generate schemas but didn't seem critical yet.

**Comment by iaincollins** [comment]
Some example schemas are now in and it now uses JSON-schema files with examples based on definitions at schema.org!

Might create something to automatically import and generate JSON-schema files from schema.org in future but that can be a new task.
